version: "3.8"

services:
  app:
    container_name: frontend
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - shopquanao-net

networks:
  shopquanao-net:
    external: true
