version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DB_HOST: pg
      MINIO_ENDPOINT: minio
    networks:
      - shopquanao-net
    volumes:
      - .:/app
      - /app/node_modules

networks:
  shopquanao-net:
    external: true